name: projetoaplicado
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.0
  flutter_neumorphic: ^3.2.0
  flutter_typeahead: ^5.0.1
  get: ^4.6.6
  google_maps_flutter: ^2.0.5
  http: ^1.1.0
  intl: ^0.18.1
  maps_launcher: ^2.2.0
  provider: ^5.0.0
  styled_text: ^8.1.0
  styled_widget: ^0.4.1
  advance_pdf_viewer: any
  syncfusion_flutter_pdfviewer: 23.2.4
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pdfs/pdfTeste.pdf
    - assets/imagens/logo.png
    - assets/imagens/logo-sem-fundo.png
    - assets/imagens/notificacao1.png
    - assets/imagens/saq.png
    - assets/imagens/icon-home.png
    - assets/imagens/icon-mapa.png
    - assets/imagens/icon-perfil.png
    - assets/imagens/icon-acontecimento.png
    - assets/imagens/icon-atendimento.png
    - assets/imagens/icon-cidadao.png
    - assets/imagens/icon-relatorio.png
    - assets/imagens/Wallpaper.png
    - assets/imagens/memeMiranha.jpg #TIRAR ESSA LINHA DEPOIS
    - assets/imagens/outroMiranha.jpg #TIRAR ESSA LINHA DEPOIS
    - assets/imagens/icon-home-normal.png
    - assets/imagens/icon-mapa-ativo.png
    - assets/imagens/icon-perfil-ativo.png
    - assets/imagens/chuva-icone.png
    - assets/imagens/fone-icone.png
    - assets/imagens/cadastro-icone.png
    - assets/imagens/icon-relatorio.png
    - assets/imagens/icon-baixar.png
    - assets/imagens/icon-camera.png
    - assets/imagens/icon-cadastro.png
    - assets/imagens/icon-pendente.png
    - assets/imagens/icon-historico.png
    - assets/imagens/icon-cadastro-inativo.png
    - assets/imagens/icon-pendente-ativo.png
    - assets/imagens/icon-historico-ativo.png
    - assets/imagens/icon-filtrar.png
    - assets/imagens/icon-pesquisar.png
    - assets/imagens/icon-calendario.png
    - assets/imagens/icon-card-comentario.png
    - assets/imagens/icon-card-tempo.png
    - assets/imagens/icon-card-vencimento.png
    - assets/imagens/icon-mapa.png
    - assets/imagens/icon-numero-protocolo.png
    - assets/imagens/icon-pesquisar.png
    - assets/imagens/icon-concluido.png
    - assets/imagens/icon-donwload.png
    - assets/imagens/icon-tipo.png
    - assets/imagens/icon-cobrade.png
    - assets/imagens/icon-evento.png
    - assets/imagens/icon-numero-protocolo.png
    - assets/imagens/icon-subgrupo.png
    - assets/imagens/icon-rg.png
    - assets/imagens/icon-cpf.png
    - assets/imagens/icon-pessoas-imovel.png
    - assets/imagens/icon-telefone.png
    - assets/imagens/icon-nome-solicitante.png
    - assets/imagens/icon-cod.png
    - assets/imagens/icon-data-vistoria.png
    - assets/imagens/icon-ocorrencia.png
    - assets/imagens/icon-endereco.png
    - assets/imagens/icon-atendente-nome.png
    - assets/imagens/icon-acontecimento-inativo.png
    - assets/imagens/icon-acontecimento-ativo.png
    - assets/imagens/icon-atendimento-inativo.png
    - assets/imagens/icon-atendimento-ativo.png
    - assets/imagens/icon-recibos-ativo.png
    - assets/imagens/icon-recibos-inativo.png
    - assets/imagens/icon-padrao-acontecimento.png
    - assets/imagens/icon-hora.png
    - assets/imagens/icon-cidadao.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
