name: projetoaplicado
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  mime: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.11
  dio: ^4.0.6
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.0
  #flutter_icons: ^1.1.0
  flutter_neumorphic: ^3.2.0
  flutter_typeahead: ^5.0.1
  get: ^4.6.6
  google_maps_flutter: ^2.0.5
  http: ^1.1.0
  intl: ^0.18.1
  maps_launcher: ^2.2.0
  provider: ^5.0.0
  styled_text: ^8.1.0
  styled_widget: ^0.4.1
  advance_pdf_viewer: ^2.0.0
  syncfusion_flutter_pdfviewer: 23.2.4
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2
  camera_camera: ^3.0.0
  image_picker: ^1.0.7
  ftpconnect: 2.0.5
  dotted_border: ^2.0.0
  share_plus: ^4.0.0
  permission_handler: ^10.0.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imagens/logo-com-fundo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/pdfs/pdfTeste.pdf
    - assets/imagens/logo.png
    - assets/imagens/logo-sem-fundo.png
    - assets/imagens/logo-com-fundo.jpg
    - assets/imagens/notificacao1.png
    - assets/imagens/saq.png
    - assets/imagens/icon-home.png
    - assets/imagens/icon-mapa.png
    - assets/imagens/icon-perfil.png
    - assets/imagens/icon-acontecimento.png
    - assets/imagens/icon-atendimento.png
    - assets/imagens/icon-cidadao.png
    - assets/imagens/icon-relatorio.png
    - assets/imagens/Wallpaper.png
    - assets/imagens/memeMiranha.jpg #TIRAR ESSA LINHA DEPOIS
    - assets/imagens/outroMiranha.jpg #TIRAR ESSA LINHA DEPOIS
    - assets/imagens/icon-home-normal.png
    - assets/imagens/icon-mapa-ativo.png
    - assets/imagens/icon-perfil-ativo.png
    - assets/imagens/chuva-icone.png
    - assets/imagens/fone-icone.png
    - assets/imagens/cadastro-icone.png
    - assets/imagens/icon-relatorio.png
    - assets/imagens/icon-baixar.png
    - assets/imagens/icon-camera.png
    - assets/imagens/icon-cadastro.png
    - assets/imagens/icon-pendente.png
    - assets/imagens/icon-historico.png
    - assets/imagens/icon-cadastro-inativo.png
    - assets/imagens/icon-pendente-ativo.png
    - assets/imagens/icon-historico-ativo.png
    - assets/imagens/icon-filtrar.png
    - assets/imagens/icon-pesquisar.png
    - assets/imagens/icon-calendario.png
    - assets/imagens/icon-card-comentario.png
    - assets/imagens/icon-card-tempo.png
    - assets/imagens/icon-card-vencimento.png
    - assets/imagens/icon-mapa.png
    - assets/imagens/icon-numero-protocolo.png
    - assets/imagens/icon-pesquisar.png
    - assets/imagens/icon-concluido.png
    - assets/imagens/icon-donwload.png
    - assets/imagens/icon-tipo.png
    - assets/imagens/icon-cobrade.png
    - assets/imagens/icon-evento.png
    - assets/imagens/icon-numero-protocolo.png
    - assets/imagens/icon-subgrupo.png
    - assets/imagens/icon-rg.png
    - assets/imagens/icon-cpf.png
    - assets/imagens/icon-pessoas-imovel.png
    - assets/imagens/icon-telefone.png
    - assets/imagens/icon-nome-solicitante.png
    - assets/imagens/icon-cod.png
    - assets/imagens/icon-data-vistoria.png
    - assets/imagens/icon-ocorrencia.png
    - assets/imagens/icon-endereco.png
    - assets/imagens/icon-atendente-nome.png
    - assets/imagens/icon-acontecimento-inativo.png
    - assets/imagens/icon-acontecimento-ativo.png
    - assets/imagens/icon-atendimento-inativo.png
    - assets/imagens/icon-atendimento-ativo.png
    - assets/imagens/icon-recibos-ativo.png
    - assets/imagens/icon-recibos-inativo.png
    - assets/imagens/icon-padrao-acontecimento.png
    - assets/imagens/icon-hora.png
    - assets/imagens/icon-cidadao.png
