// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAq_Dy3bOTrSYJ-32pt0eTjoo9NBStd3w',
    appId: '1:381013195783:web:9e3316e36e2b2fe8c77ea2',
    messagingSenderId: '381013195783',
    projectId: 'servidorimagens-defesacivil',
    authDomain: 'servidorimagens-defesacivil.firebaseapp.com',
    storageBucket: 'servidorimagens-defesacivil.appspot.com',
    measurementId: 'G-ECBPSYB6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy117H3_yl-9gfTcHhmUvcYb_KYhFnDso',
    appId: '1:381013195783:android:b06da90f5a023d11c77ea2',
    messagingSenderId: '381013195783',
    projectId: 'servidorimagens-defesacivil',
    storageBucket: 'servidorimagens-defesacivil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gl480f2n71ZCuSFUTQUkrdIiJKaaIy0',
    appId: '1:381013195783:ios:eb1b3b06feddd964c77ea2',
    messagingSenderId: '381013195783',
    projectId: 'servidorimagens-defesacivil',
    storageBucket: 'servidorimagens-defesacivil.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
